# Generated by Django 5.2.2 on 2025-06-09 15:09
# Initial migration for BabelScrib upload app
# Creates Document and UserSession models with Azure blob storage integration

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Create Document model for file upload tracking and Azure blob integration
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_id_hash', models.CharField(db_index=True, max_length=64)),
                ('blob_name', models.CharField(max_length=500)),
                ('user_blob_name', models.CharField(max_length=500)),
                ('is_translated', models.BooleanField(default=False)),
                ('translation_language', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'indexes': [
                    # Composite index for user-specific document queries
                    models.Index(fields=['user_email', 'uploaded_at'], name='upload_docu_user_em_ae5f68_idx'), 
                    # Index for user isolation queries
                    models.Index(fields=['user_id_hash'], name='upload_docu_user_id_ed1b55_idx')
                ],
            },
        ),
        # Create UserSession model for user session management and isolation
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_id_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [
                    # Index for fast session key lookups
                    models.Index(fields=['session_key'], name='upload_user_session_f7273a_idx'), 
                    # Index for user-based session queries
                    models.Index(fields=['user_email'], name='upload_user_user_em_f1118d_idx')
                ],
            },
        ),
    ]
