# Generated by Django 5.2.2 on 2025-06-24 20:33
# Architecture simplification: Remove user session management and user-specific fields
# Simplifies the data model for easier maintenance and better performance

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        # Remove UserSession model - no longer needed for simplified architecture
        migrations.DeleteModel(
            name='UserSession',
        ),
        # Remove user-specific indexes from Document model
        migrations.RemoveIndex(
            model_name='document',
            name='upload_docu_user_em_ae5f68_idx',  # user_email + uploaded_at composite index
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='upload_docu_user_id_ed1b55_idx',  # user_id_hash index
        ),
        # Remove user-specific fields from Document model
        migrations.RemoveField(
            model_name='document',
            name='user_blob_name',  # User-specific blob naming no longer needed
        ),
        migrations.RemoveField(
            model_name='document',
            name='user_email',  # User tracking removed
        ),
        migrations.RemoveField(
            model_name='document',
            name='user_id_hash',  # User isolation removed
        ),
        # Add simplified index for chronological document queries
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='upload_docu_uploade_0f101f_idx'),
        ),
    ]
