# Generated by Django 5.2.2 on 2025-06-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_delete_usersession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_id_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='upload_docu_uploade_0f101f_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='user_blob_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='document',
            name='user_id_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user_email', 'uploaded_at'], name='upload_docu_user_em_ae5f68_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user_id_hash'], name='upload_docu_user_id_ed1b55_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='upload_user_session_f7273a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user_email'], name='upload_user_user_em_f1118d_idx'),
        ),
    ]
